FROM golang:1.26.5

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends git gcc libc6-dev \
    && rm -rf /var/lib/apt/lists/*
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 40002

CMD ["dlv", "debug", "./cmd/worker", "--headless", "--listen=:40002", "--api-version=2", "--accept-multiclient", "--continue"]