services:
  postgres:
    image: postgres:16
    container_name: traceflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traceflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  kafka:
    image: apache/kafka:4.1.2
    container_name: traceflow-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
    ports:
      - "${KAFKA_PORT}:9092"
    networks:
      - traceflow-network
  
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: traceflow-opensearch
    restart: unless-stopped
    environment:
      cluster.name: ${OPENSEARCH_CLUSTER_NAME}
      node.name: ${OPENSEARCH_NODE_NAME}
      discovery.type: ${OPENSEARCH_DISCOVERY_TYPE}
      bootstrap.memory_lock: ${OPENSEARCH_BOOTSTRAP_MEMORY_LOCK}
      OPENSEARCH_JAVA_OPTS: ${OPENSEARCH_JAVA_OPTS}
      DISABLE_SECURITY_PLUGIN: ${OPENSEARCH_DISABLE_SECURITY_PLUGIN}
    ports:
      - "${OPENSEARCH_PORT}:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - traceflow-network

volumes:
    postgres_data:
      name: traceflow-postgres-data
    opensearch_data:
      name: traceflow-opensearch-data

networks:
    traceflow-network:
      name: traceflow-network
      driver: bridge